In [4]:
import numpy as np
from scipy.ndimage import convolve

# Creating a 5x5 filter for shifting an image up by 1 pixel and to the right by 2 pixels
filter_5x5 = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

# Creating a simple 5x5 test image with a single pixel in the center
test_image = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
])

# Applying the filter to the test image
shifted_image = convolve(test_image, filter_5x5, mode='constant', cval=0.0)

shifted_image



array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
K = np.array([[3, 10, 20], [18, 1, 5], [2, 30, 3]])
K

array([[ 3, 10, 20],
       [18,  1,  5],
       [ 2, 30,  3]])

In [6]:
L1 = np.array([[0, 0, 0], [72, 0, 84], [170, 26, 54]])
L1

array([[  0,   0,   0],
       [ 72,   0,  84],
       [170,  26,  54]])

In [7]:
L2 = np.array([[75, 127, 52], [87, 86, 0], [12, 188, 176]])
L2

array([[ 75, 127,  52],
       [ 87,  86,   0],
       [ 12, 188, 176]])

In [8]:
L3 = np.array([[3, 9, 208], [1, 2, 6], [22, 40, 9]])
L3

array([[  3,   9, 208],
       [  1,   2,   6],
       [ 22,  40,   9]])

In [14]:
np.square(K-L3)

array([[    0,     1, 35344],
       [  289,     1,     1],
       [  400,   100,    36]])

In [15]:
np.sum(np.square(K-L3))

36172

In [21]:
NK = np.sqrt(np.sum(np.square(K)))
NL1 = np.sqrt(np.sum(np.square(L1)))
NL2 = np.sqrt(np.sum(np.square(L2)))
NL3 = np.sqrt(np.sum(np.square(L3)))

In [39]:
K*L3

array([[   9,   90, 4160],
       [  18,    2,   30],
       [  44, 1200,   27]])

In [40]:
np.sum(K*L3)/(NK*NL3)

0.621027000462805

In [36]:
np.square(L3)


array([[    9,    81, 43264],
       [    1,     4,    36],
       [  484,  1600,    81]])

In [37]:
np.sum(np.square(L3))

45560

In [38]:

np.sqrt(np.sum(np.square(L3)))

213.44788591129216